# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "State"
  url = "about"
  weight = 10

[[main]]
  name = "Pubs&Reps"
  url = "#publications"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 40

[[main]]
  name = "News"
  url = "#news"
  weight = 50



[[main]]
  name = "CV"
  url = "pdf/cv.pdf"
  weight = 60

[[main]]
  identifier = "a-unique-reference"
  name = "English"
  url = "/"
  weight = 70

[[main]]
  parent = "a-unique-reference"
  name = "中文"
  url = "https://cn.ryoma.xyz"
  weight = 70


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
